name: Update snapshot tag

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.gitignore'
    - 'LICENSE'
    - '*.md'
    - '*.adoc'
    - '*.txt'
    - '.all-contributorsrc'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash

      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build with Maven
        run: |
          ./mvnw -B --no-transfer-progress help:evaluate -Dexpression=project.version | grep -v INFO
          ./mvnw -B --no-transfer-progress clean verify

      - name: Update tag
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
        shell: bash
        run: |
          VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=project.version | grep -v INFO)
          echo $VERSION
          if [[ $VERSION == [.0-9]*-SNAPSHOT ]]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            echo "Update tag for $VERSION"
            git push origin :refs/tags/$VERSION
            git tag -f $VERSION
            git push --tags
            echo "Delete JitPack artifacts for tag"
            curl -X "DELETE" -u${JITPACK_TOKEN} https://jitpack.io/api/builds/dev.ebullient/fc5-convert-cli/$VERSION
          fi
